<?php
/**
 * Footer template file for CodingClinicalIndicators
 *
 * Contains html for generic footer.
 * Note we must set the variable $backref so we can reach
 * relevant locations
 *
 * PHP version 8.0
 *
 * @category  CategoryName
 * @package   CodingClinicalIndicators
 * @author    Adrian P. Ireland <author@example.com>
 * @copyright 2012 Adrian P. Ireland
 * @license   http://www.gnu.org/licences/gpl 
 * @version   SVN: $Id$
 * @link      http://localhost/~adrian
 */
?>
        <footer>
          <center>
          <small>
            &copy; Adrian Ireland 2022
          </small>
          </center>
        <!--
          //<img src="<?php echo $backref;?>img/gplv3-or-later.png" alt="Gnu Licence Logo">
        -->
        </footer>
    </body>
</html>

