<?php // vim:sw=4 expandtab nu:
/**
 * Header template file
 *
 * Header template include file for coding clinical indicators
 * Contains some html to ouput at the top of most pages
 *
 * PHP version 8.0
 *
 * @category  CategoryName
 * @package   CodingClinicalIndicators
 * @author    Adrian P. Ireland <author@example.com>
 * @copyright 2012 Adrian P. Ireland
 * @license   http://www.gnu.org/LGPL LGPL
 * @version   SVN: $Id$
 * @link      http://localhost/~adrian
 */
?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Coding Clinical Indicators</title>
  <link rel="stylesheet" href="<?php echo $backref;?>css/style.css">
  <script src="<?php echo $backref;?>js/script.js" defer></script>
</head>
<body>

